# CMake generated Testfile for 
# Source directory: /home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core
# Build directory: /home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/modules/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_core "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_test_core" "--gtest_output=xml:opencv_test_core.xml")
set_tests_properties(opencv_test_core PROPERTIES  LABELS "Main;opencv_core;Accuracy" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/accuracy" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1118;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;33;ocv_add_accuracy_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;0;")
add_test(opencv_perf_core "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_perf_core" "--gtest_output=xml:opencv_perf_core.xml")
set_tests_properties(opencv_perf_core PROPERTIES  LABELS "Main;opencv_core;Performance" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/performance" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1049;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;34;ocv_add_perf_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;0;")
add_test(opencv_sanity_core "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_perf_core" "--gtest_output=xml:opencv_perf_core.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_core PROPERTIES  LABELS "Main;opencv_core;Sanity" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/sanity" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1050;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;34;ocv_add_perf_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/core/CMakeLists.txt;0;")
