# CMake generated Testfile for 
# Source directory: /home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d
# Build directory: /home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/modules/features2d
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_features2d "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_test_features2d" "--gtest_output=xml:opencv_test_features2d.xml")
set_tests_properties(opencv_test_features2d PROPERTIES  LABELS "Main;opencv_features2d;Accuracy" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/accuracy" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1118;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;941;ocv_add_accuracy_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;2;ocv_define_module;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;0;")
add_test(opencv_perf_features2d "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_perf_features2d" "--gtest_output=xml:opencv_perf_features2d.xml")
set_tests_properties(opencv_perf_features2d PROPERTIES  LABELS "Main;opencv_features2d;Performance" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/performance" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1049;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;942;ocv_add_perf_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;2;ocv_define_module;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;0;")
add_test(opencv_sanity_features2d "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/bin/opencv_perf_features2d" "--gtest_output=xml:opencv_perf_features2d.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_features2d PROPERTIES  LABELS "Main;opencv_features2d;Sanity" WORKING_DIRECTORY "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/release/test-reports/sanity" _BACKTRACE_TRIPLES "/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVUtils.cmake;935;add_test;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;1050;ocv_add_test_from_target;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/cmake/OpenCVModule.cmake;942;ocv_add_perf_tests;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;2;ocv_define_module;/home/mak5rt/git/kalman_filters/src/opencv-3.1.0/modules/features2d/CMakeLists.txt;0;")
